### ISSUE TITLE
Hiding DB Connections Strings with EnvVars

### ISSUE THREAD

**Issue by mihirpaldhikar** [MeastroZI/Grocery_Backend_Db#1]
### Use of EnvVars

Some source files contains raw credentials for database connections. Please use Environment Variables instead.

**Comment by Vinit-Pandit** [comment]
Thanks Just abhi kar deta hu

**Comment by Vinit-Pandit** [comment]
[Done](https://github.com/MeastroZI/Grocery_Backend_Db/commit/ab45c39a4fd406cfe0e4577fb6ad10c5eaecebe7)
